# Generated by Django 6.0.3 on 2026-03-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttask',
            name='cache_base_map',
            field=models.SmallIntegerField(default=0, verbose_name='天地图缓存'),
        ),
        migrations.AddField(
            model_name='reporttask',
            name='foc_depth',
            field=models.FloatField(default=10.0, verbose_name='震源深度'),
        ),
    ]
