# Generated by Django 4.2.7 on 2026-03-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reporttask_foc_depth_cache_base_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTaskRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='任务创建人')),
                ('task_id', models.BigIntegerField(verbose_name='任务id')),
                ('img1_info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='图片一说明')),
                ('img1_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片一文件地址')),
                ('img2_info', models.CharField(blank=True, max_length=512, null=True, verbose_name='图片二说明')),
                ('img2_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片二文件地址')),
                ('img3_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片三文件地址')),
                ('img4_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片四文件地址')),
                ('img5_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片五文件地址')),
                ('img6_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片六文件地址')),
                ('img7_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片七文件地址')),
                ('img8_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片八文件地址')),
                ('img9_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片九说明')),
                ('img9_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片九文件地址')),
                ('img10_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片十文件地址')),
                ('img11_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片十一说明')),
                ('img11_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片十一文件地址')),
                ('img12_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片十二说明')),
                ('img12_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片十二文件地址')),
                ('report_path', models.CharField(blank=True, max_length=100, null=True, verbose_name='报告文件地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '报告任务输出记录',
                'verbose_name_plural': '报告任务输出记录',
                'db_table': 'report_task_record',
                'indexes': [models.Index(fields=['user_id'], name='idx_record_user_id')],
            },
        ),
    ]
