# Generated by Django 4.2.7 on 2026-02-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('menu_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('route_path', models.CharField(blank=True, max_length=200, verbose_name='路由地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'sys_menu',
                'ordering': ['menu_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('role_key', models.CharField(max_length=50, unique=True, verbose_name='角色英文名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='system.menu', verbose_name='关联菜单')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('department', models.CharField(max_length=100, verbose_name='归属部门')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号码')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名称')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='用户性别')),
                ('status', models.CharField(choices=[('active', '正常'), ('inactive', '停用')], default='active', max_length=10, verbose_name='用户状态')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='岗位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='system.role', verbose_name='关联角色')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'sys_user',
            },
        ),
    ]
