# Generated by Django 4.2.26 on 2026-02-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_icon',
            field=models.CharField(blank=True, default='layui-icon-app', max_length=50, verbose_name='菜单图标'),
        ),
    ]
