# Generated by Django 4.2.26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcTif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.CharField(default='', max_length=200, verbose_name='AC数据服务器地址')),
                ('ac_name', models.CharField(max_length=200, verbose_name='AC文件名称')),
                ('ac_local_name', models.CharField(max_length=200, verbose_name='AC文件本地名称')),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='起始经度')),
                ('end_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='结束经度')),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='起始纬度')),
                ('end_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True, verbose_name='结束纬度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AC栅格数据',
                'verbose_name_plural': 'AC栅格数据',
                'db_table': 'ac_tif',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actif',
            index=models.Index(fields=['ac_name'], name='idx_ac_name'),
        ),
        migrations.AddIndex(
            model_name='actif',
            index=models.Index(fields=['start_longitude', 'end_longitude', 'start_latitude', 'end_latitude'], name='idx_longitude'),
        ),
    ]
