"""
Django settings for warehouse_manage project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 添加apps目录到Python路径
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0s@+_!ww(1mwd^!w%u85#je)s_m#dh4z01op&xm1yhpm2+*x!x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 开发环境允许所有主机；生产环境应设置为具体域名
ALLOWED_HOSTS = ['*'] if DEBUG else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'system',  # 系统管理模块
    'ac_data',  # AC栅格数据管理模块
    'report',   # 报告管理模块
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'system.middleware.LoginRequiredMiddleware',  # 登录验证中间件
]

ROOT_URLCONF = 'warehouse_manage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # 模板目录
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'warehouse_manage.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# 数据库配置：可以通过修改USE_MYSQL来切换SQLite和MySQL

USE_MYSQL = False

if USE_MYSQL:
    # MySQL数据库配置（生产环境）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('DB_NAME', 'warehouse_manage'),
            'USER': os.environ.get('DB_USER', 'root'),
            'PASSWORD': os.environ.get('DB_PASSWORD', '123456'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
else:
    # SQLite数据库配置（测试环境）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 中文

TIME_ZONE = 'Asia/Shanghai'  # 上海时区

USE_I18N = True

USE_TZ = False  # 不使用UTC时间


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session配置
SESSION_COOKIE_AGE = 30 * 60  # Session超时时间：30分钟
SESSION_SAVE_EVERY_REQUEST = True  # 每次请求都保存session
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # 浏览器关闭时session过期

# 禁用密码验证器（为了测试方便）
AUTH_PASSWORD_VALIDATORS = []

X_FRAME_OPTIONS = 'SAMEORIGIN'

# 文件上传配置
DATA_UPLOAD_MAX_MEMORY_SIZE = 209715200  # 200MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 209715200  # 200MB

# 报告文件基础存储路径
FILE_BASE_PATH = 'E:/data/report/'

# 报告Word模板路径
REPORT_TEMPLATE_PATH = 'E:/data/word/第X期 XXX地XX级地震滑坡危险性评估报告.docx'

# ============================================================
# 地图底图数据路径配置
# ============================================================
MAP_DATA_BASE_PATH = 'E:/data/geology/'  # 地图数据基础路径

# 省市县边界数据
PROVINCE_SHP_PATH = (
    MAP_DATA_BASE_PATH
    + '省市边界/全国行政区划数据最高乡镇级别/全国省份行政区划数据/省级行政区划/省.shp'
)
CITY_SHP_PATH = (
    MAP_DATA_BASE_PATH
    + '省市边界/全国行政区划数据最高乡镇级别/全国市级行政区划数据/市级行政区划/市.shp'
)
COUNTY_SHP_PATH = (
    MAP_DATA_BASE_PATH
    + '省市边界/全国行政区划数据最高乡镇级别/全国县级行政区划数据/县级行政区划/县.shp'
)

# 地级市点位数据
CITY_POINTS_SHP_PATH = MAP_DATA_BASE_PATH + '2023地级市点位数据/地级市点位数据.shp'

# 断层数据（SHP分类版）
FAULT_HOLOCENE_SHP_PATH = MAP_DATA_BASE_PATH + '断层/活动断裂-全新世.shp'
FAULT_LATE_SHP_PATH = MAP_DATA_BASE_PATH + '断层/活动断裂-晚更新世.shp'
FAULT_EARLY_SHP_PATH = MAP_DATA_BASE_PATH + '断层/活动断裂-早中更新世.shp'
# 断层数据（KMZ合并版，供 earthquake_map / earthquake_kml_map 使用）
FAULT_KMZ_PATH = MAP_DATA_BASE_PATH + '断层/全国六代图断裂.KMZ'

# 地质构造数据
GEOLOGY_TIF_PATH = MAP_DATA_BASE_PATH + '图3/地质构造/地质构造底图.tif'

# 数字高程数据
ELEVATION_TIF_PATH = MAP_DATA_BASE_PATH + '图4/全国DEM整合/全国DEM整合.tif'

# 土地利用数据
LAND_USE_TIF_PATH = MAP_DATA_BASE_PATH + '图5/土地利用/Globeland30.tif'

# 人口分布数据
POPULATION_TIF_PATH = MAP_DATA_BASE_PATH + '图6/人口公里网格分布/人口公里网格.tif'

# GDP数据
GDP_TIF_PATH = MAP_DATA_BASE_PATH + '图7/gdp2020.tif'

# 道路数据
ROAD_DATA_PATH = MAP_DATA_BASE_PATH + '全国道路网shp数据/全国道路网/'

# 滑坡斜坡数据
LANDSLIDE_SHP_PATH = MAP_DATA_BASE_PATH + '滑坡和危险斜坡/滑坡.shp'
SLOPE_SHP_PATH = MAP_DATA_BASE_PATH + '滑坡和危险斜坡/斜坡.shp'

# AC 临界加速度栅格
AC_TIF_PATH = 'C:/地质/ac/ac分割版/ac2.TIF'

# 天地图 Key
TIANDITU_TK = '1ef76ef90c6eb961cb49618f9b1a399d'

# ============================================================
# 企业级日志配置
# ============================================================
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 保留已有日志器

    # 格式化器
    'formatters': {
        'verbose': {
            # 详细格式：时间 级别 进程 线程 模块 消息
            'format': '[%(asctime)s] %(levelname)-8s %(process)d %(thread)d %(name)s:%(lineno)d - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[%(asctime)s] %(levelname)-8s %(name)s - %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },

    # 过滤器（可按需扩展）
    'filters': {},

    # 处理器
    'handlers': {
        # 控制台输出（开发/生产均保留）
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'level': 'DEBUG',
        },
        # 应用总日志文件（按天轮转，保留30天）
        'file_app': {
            'class': 'concurrent_log_handler.ConcurrentTimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'when': 'midnight',      # 按天切割
            'backupCount': 30,       # 保留最近30个文件
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'level': 'INFO',
        },
        # 报告模块专用日志文件
        'file_report': {
            'class': 'concurrent_log_handler.ConcurrentTimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'report.log'),
            'when': 'midnight',
            'backupCount': 30,
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'level': 'DEBUG',
        },
        # 错误日志文件
        'file_error': {
            'class': 'concurrent_log_handler.ConcurrentTimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'when': 'midnight',
            'backupCount': 30,
            'encoding': 'utf-8',
            'formatter': 'verbose',
            'level': 'ERROR',
        },
    },

    # 日志器
    'loggers': {
        # 根日志器
        '': {
            'handlers': ['console', 'file_app', 'file_error'],
            'level': 'INFO',
            'propagate': False,
        },
        # 报告管理模块日志器
        'report': {
            'handlers': ['console', 'file_report', 'file_error'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Django 框架日志
        'django': {
            'handlers': ['console', 'file_app'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django 请求日志
        'django.request': {
            'handlers': ['file_error'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}